name: Action Practice


on:
  push:
  schedule:
   - cron: "*/5 * * * *"
  

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install huggingface_hub "streamlink>=6.8.2" "httpx[http2]>=0.27.0" "ffmpeg-python>=0.2.0" "loguru>=0.7.2" "jsonpath-ng>=1.6.1" "jsengine>=1.0.7.post1" "quickjs>=1.19.4" "httpx-socks[asyncio]>=0.9.1" nest_asyncio
      - name: Run
        run: python3 ../live_recorder.py --bearer_token --encode_code


      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git pull
           
          
          git reset --mixed master
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push
